<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-KafkaDotNet.OrderProcessor-ad39668d-0096-44c3-9547-ac8c5f0c5684</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KafkaDotNet.Contracts\KafkaDotNet.Contracts.csproj" />
    <ProjectReference Include="..\KafkaDotNet.Messaging\KafkaDotNet.Messaging.csproj" />
  </ItemGroup>
</Project>
